version: "3"
services:
  web:
    image: itvis/financephp
#    ports: 
#       - "80:8080"
#       - "443:8443"
    environment:
       - VIRTUAL_HOST=
    networks:
       - nginx-proxy
    volumes:
       - financephp_www:/var/www/html/

networks:
  nginx-proxy:
    external:
      name: nginx-proxy

volumes:
  financephp_www:
